#pragma once

#define UNIVERSE_SCALE 0.002f


/**
* This file contains planet information.
*/

#define DEFAULT_MOON_TEXTURE_FOLDER "moonTextures/"
#define DEFAULT_MOON_TEXTURE_SIZE 128
#define DEFAULT_MOON_SIZE (UNIVERSE_SCALE*1737.0)
#define DEFAULT_MOON_MASS (UNIVERSE_SCALE*1000.0)
#define DEFAULT_MOON_DISTANCE (UNIVERSE_SCALE*4000.0)


// SUN
#define SUN_TEXTURE_FOLDER "sunTextures/"
#define SUN_TEXTURE_SIZE 512
#define SUN_SIZE (UNIVERSE_SCALE*696000.0)
#define SUN_MASS (UNIVERSE_SCALE*10000.0)
#define SUN_STARTING_X 0
#define SUN_STARTING_Y 0
#define SUN_STARTING_Z 0

// Mercury
#define MERCURY_TEXTURE_FOLDER "mercuryTextures/"
#define MERCURY_TEXTURE_SIZE 1024
#define MERCURY_SIZE (UNIVERSE_SCALE*2440.0)
#define MERCURY_MASS (UNIVERSE_SCALE*2000.0)
#define MERCURY_DISTANCE_FROM_SUN (UNIVERSE_SCALE*720000.0)

// Venus
#define VENUS_TEXTURE_FOLDER "venusTextures/"
#define VENUS_TEXTURE_SIZE 1024
#define VENUS_SIZE (UNIVERSE_SCALE*6052.0)
#define VENUS_MASS (UNIVERSE_SCALE*4000.0)
#define VENUS_DISTANCE_FROM_SUN (UNIVERSE_SCALE*750000.0)

// EARTH
#define EARTH_TEXTURE_FOLDER "earthTextures/"
#define EARTH_TEXTURE_SIZE 512
#define EARTH_SIZE (UNIVERSE_SCALE*6378.0)
#define EARTH_MASS (UNIVERSE_SCALE*5000.0)
#define EARTH_DISTANCE_FROM_SUN (UNIVERSE_SCALE*800000.0)

// earth's moon
#define MOON_TEXTURE_FOLDER "moonTextures/"
#define MOON_TEXTURE_SIZE 128
#define MOON_SIZE (UNIVERSE_SCALE*1737.0)
#define MOON_MASS (UNIVERSE_SCALE*1000.0)
#define MOON_DISTANCE_FROM_EARTH (UNIVERSE_SCALE*20000.0)

// Mars
#define MARS_TEXTURE_FOLDER "marsTextures/"
#define MARS_TEXTURE_SIZE 512
#define MARS_SIZE (UNIVERSE_SCALE*3378.0)
#define MARS_MASS (UNIVERSE_SCALE*3000.0)
#define MARS_DISTANCE_FROM_SUN (UNIVERSE_SCALE*900000.0)

#define MARS_MOONS 2

// Jupiter
#define JUPITER_TEXTURE_FOLDER "jupiterTextures/"
#define JUPITER_TEXTURE_SIZE 512
#define JUPITER_SIZE (UNIVERSE_SCALE*71492.0)
#define JUPITER_MASS (UNIVERSE_SCALE*9000.0)
#define JUPITER_DISTANCE_FROM_SUN (UNIVERSE_SCALE*1400000.0)

#define JUPITER_MOONS 16

// Saturn
#define SATURN_TEXTURE_FOLDER "saturnTextures/"
#define SATURN_TEXTURE_SIZE 256
#define SATURN_SIZE (UNIVERSE_SCALE*60268.0)
#define SATURN_MASS (UNIVERSE_SCALE*8000.0)
#define SATURN_DISTANCE_FROM_SUN (UNIVERSE_SCALE*1900000.0)

#define SATURN_MOONS 63

// Uranus
#define URANUS_TEXTURE_FOLDER "uranusTextures/"
#define URANUS_TEXTURE_SIZE 256
#define URANUS_SIZE (UNIVERSE_SCALE*25559.0)
#define URANUS_MASS (UNIVERSE_SCALE*6000.0)
#define URANUS_DISTANCE_FROM_SUN (UNIVERSE_SCALE*2300000.0)

#define URANUS_MOONS 27

// Neptune
#define NEPTUNE_TEXTURE_FOLDER "neptuneTextures/"
#define NEPTUNE_TEXTURE_SIZE 256
#define NEPTUNE_SIZE (UNIVERSE_SCALE*24766.0)
#define NEPTUNE_MASS (UNIVERSE_SCALE*7000.0)
#define NEPTUNE_DISTANCE_FROM_SUN (UNIVERSE_SCALE*2550000.0)

#define NEPTUNE_MOONS 13